# Generated by Django 4.0.10 on 2024-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
