# Generated by Django 4.0.10 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tickets', '0003_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('cinema_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('distance', models.FloatField()),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
